/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#FFFFFF",
        "tertiary-fixed": "#ffdad4",
        "error": "#ba1a1a",
        "on-primary-container": "#ff907f",
        "on-background": "#121d26",
        "surface-tint": "#b52619",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f7f9ff",
        "on-tertiary-fixed-variant": "#862116",
        "surface-container": "#e4effd",
        "primary-fixed-dim": "#ffb4a8",
        "primary-container": "#8b0000",
        "inverse-surface": "#27313c",
        "primary": "#610000",
        "surface-container-low": "#edf4ff",
        "on-secondary-container": "#735a00",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "tertiary": "#600201",
        "surface-variant": "#d9e3f1",
        "on-surface": "#121d26",
        "tertiary-container": "#801c12",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb4a8",
        "page-bg": "#F7F5F0",
        "secondary-fixed-dim": "#ecc246",
        "inverse-primary": "#ffb4a8",
        "on-secondary-fixed-variant": "#584400",
        "surface-container-high": "#dfe9f7",
        "secondary-fixed": "#ffe08e",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary": "#755b00",
        "border-subtle": "#E5E0D8",
        "inverse-on-surface": "#e8f2ff",
        "on-tertiary-fixed": "#410000",
        "background": "#f7f9ff",
        "on-secondary-fixed": "#241a00",
        "on-tertiary-container": "#ff907f",
        "on-primary-fixed-variant": "#920703",
        "on-primary-fixed": "#410000",
        "secondary-container": "#fed255",
        "on-surface-variant": "#5a403c",
        "surface-dim": "#d1dbe8",
        "text-muted": "#6B7280",
        "primary-fixed": "#ffdad4",
        "surface-container-highest": "#d9e3f1",
        "outline": "#8e706b",
        "outline-variant": "#e3beb8",
        "red-tint": "#F8EAEA"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "margin-tablet": "32px",
        "unit": "8px",
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "title-md": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
        "title-lg": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
