CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS report_db;
CREATE DATABASE IF NOT EXISTS evidence_db;
CREATE DATABASE IF NOT EXISTS dispatch_db;
CREATE DATABASE IF NOT EXISTS dashboard_db;
CREATE DATABASE IF NOT EXISTS admin_db;
